version: '3.3'

services:
  mysqldd:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./db_data/:/var/lib/mysql # monsta local onde m
      
      - ./dump:/docker-entrypoint-initdb.d # pasta onde vc vai colocar os scripts .sql que quer executar na inicializacao 
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: classificados
      MYSQL_USER: giorgiogay
      MYSQL_PASSWORD: piroca
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - mysqldd
    ports:
      - 1234:80
    environment:
      - PMA_ARBITRARY=1
  web:
    image: nginx
    volumes:
      - ./app:/app
      - ./site.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - app-network
  php:
    image: php:fpm
    volumes:
      - ./app:/app
    networks:
      - app-network

networks:
    app-network:
        driver: bridge


