version: "3"
services:
  php-apache:
    build: .
    ports:
     - "8080:80"
    links:
     - mysqldd 
    volumes:
     - ./app:/var/www/html
  mysqldd:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: classificados
      MYSQL_USER: giorgio
      MYSQL_PASSWORD: giorgio
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - mysqldd
    ports:
      - "1234:80"
    environment:
      - PMA_ARBITRARY=1