version: '3'
volumes:
  dados:
services:
  db:
    image: mysql:5.7
    ports:  
      - "3306:3306"  
    environment:  
      - MYSQL_ROOT_PASSWORD=root  
      - MYSQL_DATABASE=mydatabase  
    volumes:  
      - dados:/var/lib/mysql
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      