<<<<<<< HEAD
version: '3'
volumes:
  dados:
services:
  db:
    image: mysql:5.7
    ports:  
      - "3306:3306"  
    environment:  
      - MYSQL_ROOT_PASSWORD=root  
      - MYSQL_DATABASE=mydatabase  
    volumes:  
      - dados:/var/lib/mysql
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      
=======
version: '3.1'

services:
  db:
    image: mysql:5.7
    env_file:
      - .env
>>>>>>> 85e7011d2324c8ad3ab4b45baebe70f06c4f6fbc
